-- Insert sample services for testing
INSERT INTO services (
  name, 
  specialty, 
  category, 
  description, 
  location, 
  phone, 
  email, 
  website, 
  contact_person, 
  languages, 
  verified, 
  featured, 
  rating, 
  reviews_count
) VALUES 
(
  'Dragon Legal Services',
  'Immigration Law',
  'legal',
  'Professional immigration law services for Chinese community in the UK. Specializing in visa applications, citizenship, and family reunion cases.',
  'London',
  '+44 20 7123 4567',
  'info@dragonlegal.co.uk',
  'https://dragonlegal.co.uk',
  'David Chen',
  ARRAY['English', 'Mandarin', 'Cantonese'],
  true,
  true,
  4.8,
  25
),
(
  'Harmony Medical Centre',
  'General Practice',
  'medical',
  'Chinese-speaking medical services including general practice, traditional Chinese medicine, and health consultations.',
  'Manchester',
  '+44 161 234 5678',
  'appointments@harmonymedical.co.uk',
  'https://harmonymedical.co.uk',
  'Dr. Lisa Wong',
  ARRAY['English', 'Mandarin', 'Cantonese'],
  true,
  false,
  4.6,
  18
),
(
  'Golden Finance Advisors',
  'Financial Planning',
  'financial',
  'Comprehensive financial planning and investment advice for Chinese families in the UK. Specializing in property investment and retirement planning.',
  'Birmingham',
  '+44 121 345 6789',
  'contact@goldenfinance.co.uk',
  'https://goldenfinance.co.uk',
  'Michael Wang',
  ARRAY['English', 'Mandarin'],
  true,
  false,
  4.5,
  12
),
(
  'Bright Future Education',
  'Private Tutoring',
  'education',
  'Private tutoring services for Chinese students. Offering support in Maths, Science, English, and university applications.',
  'Edinburgh',
  '+44 131 456 7890',
  'info@brightfuture.co.uk',
  'https://brightfuture.co.uk',
  'Sarah Li',
  ARRAY['English', 'Mandarin', 'Cantonese'],
  false,
  false,
  4.7,
  8
); 