// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spbbiaqrybijcnopbiej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwYmJpYXFyeWJpamNub3BiaWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTA0MzksImV4cCI6MjA2NzkyNjQzOX0.zMsT9WcF4epUVmJ3J_4SQqkU_6gDCttm9rZXlyi76SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});